#!/usr/bin/env python3
"""Generate and validate LongLive2 inference configs for repo-run workflows."""

from __future__ import annotations

import argparse
import csv
import json
import math
import tempfile
from dataclasses import dataclass
from pathlib import Path


DEFAULT_REPO_REF = "536d1b9a3563b078bea378aa968416543fd9d669"
DEFAULT_MODEL_NAME = "Wan2.2-TI2V-5B"
DEFAULT_SCENE_CUT_PREFIX = "The scene transitions. "
DEFAULT_NEGATIVE_PROMPT = (
    "overexposed, static, blurry details, subtitles, low quality, jpeg artifacts, "
    "deformed hands, deformed face, malformed limbs, cluttered background"
)


@dataclass(frozen=True)
class ConfigSpec:
    profile: str
    height: int
    width: int
    frames: int
    sp_size: int
    dp_size: int
    prompt_path: Path
    output_folder: Path
    generator_ckpt: str
    lora_ckpt: str
    sampling_steps: int
    model_num_heads: int
    num_frame_per_block: int
    guidance_scale: float
    seed: int
    vae_device: str
    torch_compile: str


def valid_sp_sizes(model_num_heads: int, num_frame_per_block: int) -> list[int]:
    base = math.gcd(model_num_heads, num_frame_per_block)
    return [size for size in range(1, base + 1) if base % size == 0]


def _bool_text(value: bool) -> str:
    return "true" if value else "false"


def _yaml_scalar(value: str | int | float | bool) -> str:
    if isinstance(value, bool):
        return _bool_text(value)
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def _normalize_profile(raw: str) -> str:
    profile = raw.strip().lower().replace("-", "_")
    if profile in {"bf16", "bf16_sp"}:
        return "bf16_sp"
    if profile in {"nvfp4", "nvfp4_s4", "nvfp4_4step", "nvfp4_s4_sp"}:
        return "nvfp4_s4"
    if profile in {"nvfp4_s2", "nvfp4_2step", "nvfp4_s2_sp"}:
        return "nvfp4_s2"
    raise ValueError(f"unsupported profile '{raw}'")


def _num_blocks(frames: int, num_frame_per_block: int) -> int:
    if frames <= 0 or num_frame_per_block <= 0:
        raise ValueError("frames and num_frame_per_block must be positive")
    if frames % num_frame_per_block != 0:
        raise ValueError(f"frames must be divisible by num_frame_per_block={num_frame_per_block}")
    return frames // num_frame_per_block


def validate_spec(spec: ConfigSpec) -> None:
    if spec.height <= 0 or spec.width <= 0:
        raise ValueError("height and width must be positive")
    if spec.height % 16 != 0 or spec.width % 16 != 0:
        raise ValueError("height and width must be divisible by 16")
    if spec.frames <= 0:
        raise ValueError("frames must be positive")
    if spec.frames % spec.num_frame_per_block != 0:
        raise ValueError(f"frames must be divisible by num_frame_per_block={spec.num_frame_per_block}")
    if spec.sp_size <= 0 or spec.dp_size <= 0:
        raise ValueError("sp_size and dp_size must be positive")
    allowed = valid_sp_sizes(spec.model_num_heads, spec.num_frame_per_block)
    if spec.sp_size not in allowed:
        raise ValueError(
            f"sp_size={spec.sp_size} must divide gcd(model_num_heads={spec.model_num_heads}, "
            f"num_frame_per_block={spec.num_frame_per_block}); valid={allowed}"
        )
    if not str(spec.prompt_path):
        raise ValueError("prompt_path is required")
    if not str(spec.output_folder):
        raise ValueError("output_folder is required")


def render_config(spec: ConfigSpec) -> str:
    validate_spec(spec)
    latent_h = spec.height // 16
    latent_w = spec.width // 16
    model_quant = spec.profile.startswith("nvfp4")
    kv_quant = model_quant and spec.sp_size == 1
    streaming_vae = bool(spec.vae_device)

    lines: list[str] = [
        "# Generated by VideoDiffusion/longlive2_config.py; safe to overwrite.",
        "model_kwargs:",
        f"  model_name: {_yaml_scalar(DEFAULT_MODEL_NAME)}",
        "  timestep_shift: 5.0",
        f"  num_frame_per_block: {spec.num_frame_per_block}",
        "  local_attn_size: 32",
        "  sink_size: 8",
        "",
        f"sp_size: {spec.sp_size}",
        f"dp_size: {spec.dp_size}",
        "auto_sp_remainder: false",
        f"model_num_heads: {spec.model_num_heads}",
        "",
        "use_ema: false",
        f"output_folder: {_yaml_scalar(str(spec.output_folder))}",
        "num_samples: 1",
        "save_latents_only: false",
        "save_with_index: true",
        "inference_iter: -1",
        f"num_output_frames: {spec.frames}",
        "merge_lora: false",
        "chunks_per_shot: 0",
        f"scene_cut_prefix: {_yaml_scalar(DEFAULT_SCENE_CUT_PREFIX)}",
        "",
        "data:",
        f"  data_path: {_yaml_scalar(str(spec.prompt_path))}",
        "  image_or_video_shape:",
        "  - 1",
        f"  - {spec.frames}",
        "  - 48",
        f"  - {latent_h}",
        f"  - {latent_w}",
        "",
        "inference:",
        f"  sampling_steps: {spec.sampling_steps}",
        "  sink_size: 8",
        f"  guidance_scale: {spec.guidance_scale}",
        "  multi_shot_sink: true",
        "  multi_shot_rope_offset: 8",
        f"  kv_quant: {_bool_text(kv_quant)}",
        "  kv_quant_scale_rule: mse",
        "  kv_quant_backend: cuda",
        f"  streaming_vae: {_bool_text(streaming_vae)}",
        f"  async_vae: {_bool_text(streaming_vae)}",
        "  vae_type: wan",
        f"  vae_device: {_yaml_scalar(spec.vae_device)}",
        f"  negative_prompt: {_yaml_scalar(DEFAULT_NEGATIVE_PROMPT)}",
        "",
        "checkpoints:",
        f"  generator_ckpt: {_yaml_scalar(spec.generator_ckpt)}",
    ]
    if spec.lora_ckpt:
        lines.append(f"  lora_ckpt: {_yaml_scalar(spec.lora_ckpt)}")
    else:
        lines.append("  lora_ckpt: null")

    lines.extend(
        [
            "",
            f"model_quant: {_bool_text(model_quant)}",
            "model_quant_use_transformer_engine: false",
            "model_quant_te_inference_only: true",
            "model_quant_te_low_precision_weights: true",
            "model_quant_te_fallback_to_fouroversix: false",
            "model_quant_scale_rule: mse",
            "model_quant_activation_scale_rule: mse",
            "model_quant_weight_scale_rule: mse",
            "model_quant_gradient_scale_rule: mse",
            "",
            f"torch_compile: {_yaml_scalar(spec.torch_compile)}",
            "torch_compile_min_samples: 2",
            "torch_compile_target: generator_model",
            "torch_compile_backend: inductor",
            "torch_compile_mode: max-autotune-no-cudagraphs",
            "torch_compile_fullgraph: false",
            "torch_compile_dynamic: false",
            "torch_compile_suppress_errors: true",
        ]
    )

    if spec.lora_ckpt:
        lines.extend(
            [
                "",
                "adapter:",
                "  type: lora",
                "  rank: 128",
                "  alpha: 128",
                "  dropout: 0.0",
                "  dtype: bfloat16",
                "  apply_to_critic: true",
                "  verbose: true",
            ]
        )

    lines.extend(["", "logging:", f"  seed: {spec.seed}", ""])
    return "\n".join(lines)


def write_prompt_file(path: Path, prompt: str, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(prompt.rstrip() + "\n", encoding="utf-8")


def _coalesce_block_prompts(block_prompts: list[str]) -> tuple[list[str], list[int]]:
    if not block_prompts:
        raise ValueError("at least one prompt block is required")
    prompts: list[str] = []
    durations: list[int] = []
    current = block_prompts[0]
    count = 1
    for prompt in block_prompts[1:]:
        if prompt == current:
            count += 1
            continue
        prompts.append(current)
        durations.append(count)
        current = prompt
        count = 1
    prompts.append(current)
    durations.append(count)
    return prompts, durations


def _read_schedule_csv(path: Path, num_blocks: int, default_prompt: str) -> list[str]:
    if not path.is_file():
        raise ValueError(f"schedule CSV not found: {path}")
    block_prompts = [default_prompt] * num_blocks
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        required = {"start_chunk", "end_chunk", "prompt"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(f"schedule CSV missing required columns: {sorted(missing)}")
        for row_idx, row in enumerate(reader, start=2):
            prompt = (row.get("prompt") or "").strip()
            if not prompt:
                continue
            try:
                start = int(row.get("start_chunk") or 0)
                end = int(row.get("end_chunk") or start)
            except ValueError as exc:
                raise ValueError(f"invalid chunk range at schedule row {row_idx}") from exc
            if start < 0 or end < start:
                raise ValueError(f"invalid chunk range at schedule row {row_idx}: {start}..{end}")
            for chunk_idx in range(start, min(end, num_blocks - 1) + 1):
                block_prompts[chunk_idx] = prompt
    return block_prompts


def _durations_from_shots(shots: list[str], durations: list[int], num_blocks: int) -> list[int]:
    if not shots:
        raise ValueError("at least one shot prompt is required")
    if durations:
        if len(durations) != len(shots):
            raise ValueError("--shot-duration count must match --shot-prompt count")
        if any(d <= 0 for d in durations):
            raise ValueError("shot durations must be positive")
        if sum(durations) != num_blocks:
            raise ValueError(f"shot durations must sum to num_blocks={num_blocks}")
        return durations
    base, extra = divmod(num_blocks, len(shots))
    return [base + (1 if i < extra else 0) for i in range(len(shots))]


def write_prompt_schedule_dir(
    path: Path,
    *,
    shot_prompts: list[str],
    shot_durations: list[int],
    scene_cut_prefix: str,
) -> None:
    sample_dir = path / "caption" / "sample_000"
    sample_dir.mkdir(parents=True, exist_ok=True)
    for old in sample_dir.glob("*.json"):
        old.unlink()
    for idx, prompt in enumerate(shot_prompts):
        payload = {"caption": prompt}
        (sample_dir / f"{idx:03d}.json").write_text(json.dumps(payload, ensure_ascii=False) + "\n", encoding="utf-8")
    (sample_dir / "shot_durations.txt").write_text(
        " ".join(str(x) for x in shot_durations) + "\n",
        encoding="utf-8",
    )
    manifest = {
        "format": "longlive2_multishot_caption_dir",
        "scene_cut_prefix": scene_cut_prefix,
        "shot_count": len(shot_prompts),
        "shot_durations": shot_durations,
        "prompt_blocks": sum(shot_durations),
        "note": "LongLive2 reads this through MultiTextConcatDataset directory mode.",
    }
    (path / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _build_spec(args: argparse.Namespace) -> ConfigSpec:
    profile = _normalize_profile(args.profile)
    sampling_steps = args.sampling_steps
    if sampling_steps is None:
        sampling_steps = 2 if profile == "nvfp4_s2" else 4
    generator_ckpt = args.generator_ckpt
    if not generator_ckpt:
        generator_ckpt = (
            "checkpoints/longlive2_5b_nvfp4_2step/generator.pt"
            if profile == "nvfp4_s2"
            else "checkpoints/longlive2_5b/generator.pt"
        )
        if profile == "nvfp4_s4":
            generator_ckpt = "checkpoints/longlive2_5b_nvfp4_4step/generator.pt"
    return ConfigSpec(
        profile=profile,
        height=args.height,
        width=args.width,
        frames=args.frames,
        sp_size=args.sp_size,
        dp_size=args.dp_size,
        prompt_path=Path(args.prompt_path),
        output_folder=Path(args.output_folder),
        generator_ckpt=generator_ckpt,
        lora_ckpt=args.lora_ckpt,
        sampling_steps=int(sampling_steps),
        model_num_heads=args.model_num_heads,
        num_frame_per_block=args.num_frame_per_block,
        guidance_scale=args.guidance_scale,
        seed=args.seed,
        vae_device=args.vae_device,
        torch_compile=args.torch_compile,
    )


def command_generate(args: argparse.Namespace) -> int:
    spec = _build_spec(args)
    text = render_config(spec)
    num_blocks = _num_blocks(spec.frames, spec.num_frame_per_block)
    wrote_schedule = False
    if args.schedule_csv:
        block_prompts = _read_schedule_csv(Path(args.schedule_csv).expanduser(), num_blocks, args.prompt)
        shot_prompts, shot_durations = _coalesce_block_prompts(block_prompts)
        write_prompt_schedule_dir(
            Path(args.prompt_path),
            shot_prompts=shot_prompts,
            shot_durations=shot_durations,
            scene_cut_prefix=args.scene_cut_prefix,
        )
        wrote_schedule = True
    elif args.shot_prompt:
        shot_prompts = [str(item).strip() for item in args.shot_prompt if str(item).strip()]
        shot_durations = _durations_from_shots(shot_prompts, [int(x) for x in args.shot_duration], num_blocks)
        write_prompt_schedule_dir(
            Path(args.prompt_path),
            shot_prompts=shot_prompts,
            shot_durations=shot_durations,
            scene_cut_prefix=args.scene_cut_prefix,
        )
        wrote_schedule = True
    elif args.write_prompt:
        write_prompt_file(Path(args.prompt_path), args.prompt, overwrite=args.overwrite_prompt)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    if args.print_json:
        payload = {
            "config_path": str(out),
            "profile": spec.profile,
            "entrypoint": "inference_sp.py" if spec.sp_size > 1 else "inference.py",
            "nproc_per_node": spec.sp_size * spec.dp_size,
            "height": spec.height,
            "width": spec.width,
            "frames": spec.frames,
            "latent_shape": [1, spec.frames, 48, spec.height // 16, spec.width // 16],
            "valid_sp_sizes": valid_sp_sizes(spec.model_num_heads, spec.num_frame_per_block),
            "prompt_mode": "directory_schedule" if wrote_schedule else "txt",
            "prompt_blocks": num_blocks,
        }
        print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


def command_selftest() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        spec = ConfigSpec(
            profile="bf16_sp",
            height=704,
            width=1280,
            frames=128,
            sp_size=2,
            dp_size=1,
            prompt_path=root / "prompt.txt",
            output_folder=root / "out",
            generator_ckpt="checkpoints/generator.pt",
            lora_ckpt="checkpoints/lora.pt",
            sampling_steps=4,
            model_num_heads=24,
            num_frame_per_block=8,
            guidance_scale=1.0,
            seed=0,
            vae_device="",
            torch_compile="false",
        )
        rendered = render_config(spec)
        assert "sp_size: 2" in rendered
        assert "  - 44" in rendered
        assert "  - 80" in rendered
        assert valid_sp_sizes(24, 8) == [1, 2, 4, 8]
        schedule_csv = root / "schedule.csv"
        schedule_csv.write_text(
            "cue_id,start_chunk,end_chunk,prompt\n"
            "a,1,3,calm prompt\n"
            "b,4,7,active prompt\n",
            encoding="utf-8",
        )
        block_prompts = _read_schedule_csv(schedule_csv, 8, "base prompt")
        shot_prompts, shot_durations = _coalesce_block_prompts(block_prompts)
        write_prompt_schedule_dir(
            root / "schedule_dir",
            shot_prompts=shot_prompts,
            shot_durations=shot_durations,
            scene_cut_prefix=DEFAULT_SCENE_CUT_PREFIX,
        )
        assert (root / "schedule_dir" / "caption" / "sample_000" / "000.json").is_file()
        assert sum(shot_durations) == 8
        try:
            validate_spec(
                ConfigSpec(
                    **{
                        **spec.__dict__,
                        "sp_size": 3,
                    }
                )
            )
        except ValueError as exc:
            assert "sp_size=3" in str(exc)
        else:
            raise AssertionError("invalid sp_size was accepted")
    print("[longlive2-config-selftest] ok")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="Generate a LongLive2 inference config")
    gen.add_argument("--profile", default="bf16_sp", help="bf16_sp, nvfp4_s4, or nvfp4_s2")
    gen.add_argument("--out", required=True)
    gen.add_argument("--prompt-path", required=True)
    gen.add_argument("--output-folder", required=True)
    gen.add_argument("--prompt", default="A reactive neon tunnel breathes with smooth cinematic motion.")
    gen.add_argument("--write-prompt", action="store_true")
    gen.add_argument("--overwrite-prompt", action="store_true")
    gen.add_argument("--schedule-csv", default="", help="EEG schedule CSV with start_chunk,end_chunk,prompt")
    gen.add_argument("--shot-prompt", action="append", default=[], help="Multi-shot prompt; may be repeated")
    gen.add_argument("--shot-duration", action="append", type=int, default=[], help="Block count for each --shot-prompt")
    gen.add_argument("--scene-cut-prefix", default=DEFAULT_SCENE_CUT_PREFIX)
    gen.add_argument("--height", type=int, default=704)
    gen.add_argument("--width", type=int, default=1280)
    gen.add_argument("--frames", type=int, default=128)
    gen.add_argument("--sp-size", type=int, default=2)
    gen.add_argument("--dp-size", type=int, default=1)
    gen.add_argument("--model-num-heads", type=int, default=24)
    gen.add_argument("--num-frame-per-block", type=int, default=8)
    gen.add_argument("--sampling-steps", type=int, default=None)
    gen.add_argument("--guidance-scale", type=float, default=1.0)
    gen.add_argument("--seed", type=int, default=0)
    gen.add_argument("--generator-ckpt", default="")
    gen.add_argument("--lora-ckpt", default="")
    gen.add_argument("--vae-device", default="")
    gen.add_argument("--torch-compile", default="false")
    gen.add_argument("--print-json", action="store_true")
    gen.set_defaults(func=command_generate)

    selftest = sub.add_parser("selftest", help="Run no-cost checks")
    selftest.set_defaults(func=lambda _args: command_selftest())
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        return int(args.func(args))
    except ValueError as exc:
        parser.error(str(exc))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
